name: SonarCloud Scan

on:
  push:
    branches:
      - main

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

    #   - name: Install dependencies
    #     run: composer install

      - name: Update dependencies
        run: composer update

      - name: Run PHPUnit tests and generate coverage
        run: vendor/bin/phpunit --coverage-clover=coverage.xml

    # Check test coverage
      - name: Check test coverage
        uses: johanvanhelden/gha-clover-test-coverage-check@v1
        id: coverage
        with:
            percentage: "1"
            filename: "coverage.xml"
      - uses: actions/upload-artifact@v3
        with:
            name: coverage
            path: coverage.xml

      - name: List Files
        run: pwd; ls -la

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
            SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
